asdf

diff --git a/.github/workflows/auto-release.yaml b/.github/workflows/auto-release.yaml
--- a/.github/workflows/auto-release.yaml
+++ b/.github/workflows/auto-release.yaml
@@ -215,14 +215,12 @@ jobs:
       - name: Prepare Chart
         continue-on-error: false
         run: |
-          pwd 
-          ls 
           cd charts
-          ls 
-          cat Makefile
           make clean
           make
-          ls *.tgz &>/dev/null && echo "failed to generate chart" && exit 1
+          ls *.tgz &>/dev/null && exit 0
+          echo "failed to generate chart"
+          exit 1
 
       - name: Prepare Index
         continue-on-error: false
