license

diff --git a/.github/workflows/lint-license.yaml b/.github/workflows/lint-license.yaml
--- a/.github/workflows/lint-license.yaml
+++ b/.github/workflows/lint-license.yaml
@@ -27,7 +27,7 @@ jobs:
         continue-on-error: false
         run: |
           FILE_LIST=$( egrep -i "Apache-2.0|Copyright"  ./*  --exclude-dir=./vendor  -RHL --include=*.go  2>/dev/null )
-          (( $? == 0 )) && echo "error, failed to grep " && exit 1
+          (( $? != 0 )) && echo "error, failed to grep " && exit 1
           if [ -n "$FILE_LIST" ]; then
               echo "error, found go file missing licnese"
               exit 1
