dasf

diff --git a/.github/workflows/release-chart.yaml b/.github/workflows/release-chart.yaml
--- a/.github/workflows/release-chart.yaml
+++ b/.github/workflows/release-chart.yaml
@@ -61,22 +61,26 @@ jobs:
       - name: Prepare Chart
         continue-on-error: false
         run: |
-          chart_dir=${{ matrix.chart_dir }}
-          [ ! -d "${chart_dir}" ] && echo "error, fail to find directory ${chart_dir}" && exit 1
-          mkdir _tmp
-          cd _tmp
-          helm package ../${chart_dir}
+          cd charts
+          make clean
+          make
+          if ! ls *.tgz &>/dev/null ; then
+            echo "failed to generate chart"
+            exit 1
+          fi
           cd ..
           mkdir -p docs/charts
-          mv _tmp/*.tgz docs/charts
-          rm -rf _tmp
+          mv charts/*.tgz docs/charts
+          git checkout -- charts
 
       - name: Prepare Index
         continue-on-error: false
         run: |
+          #rebuild index for docs/charts
           cd docs
           helm repo index  ./charts  --url ${{ steps.get_base_url.outputs.url }}/charts
           mv ./charts/index.yaml ./
+
 
       - name: Upload Chart Package
         uses: actions/upload-artifact@v3.0.0
